import { tmpdir } from 'node:os';
import { join } from 'node:path';

export const CURSOR_FILE = 'cursor';

const RUNTIME_DIR = join(tmpdir(), 'obsidian-neovim-sidecar');

export const CURSOR_SYNC_PATHS = {
	dir: RUNTIME_DIR,
	cursor: join(RUNTIME_DIR, CURSOR_FILE),
	lua: join(RUNTIME_DIR, 'sidecar.lua'),
	socket: join(RUNTIME_DIR, 'nvim.sock'),
};

// Whichever side moves last wins. Applying a move on one side makes that side
// emit its own change event, so each side ignores incoming moves for a moment
// after it applies one -- otherwise the echo bounces back and the two fight.
export const SUPPRESS_MS = 40;
export const DEBOUNCE_MS = 8;

export function buildSidecarLua(vaultRoot = '', cursorSync = false, autosave = false): string {
	const escapedVaultRoot = vaultRoot.replace(/'/g, "\\'");
	return `-- generated by obsidian-neovim-sidecar; edits are overwritten
local uv = vim.uv or vim.loop
local cursor_file = '${CURSOR_SYNC_PATHS.cursor}'
local vault_root = '${escapedVaultRoot}'
local suppress_until = 0
local timer = nil
local cursor_sync_enabled = ${cursorSync ? 'true' : 'false'}

vim.o.hidden = true
vim.o.autoread = true

pcall(vim.fn.serverstart, '${CURSOR_SYNC_PATHS.socket}')

local function push()
  if not cursor_sync_enabled then
    return
  end
  if uv.now() < suppress_until then
    return
  end
  local path = vim.api.nvim_buf_get_name(0)
  if path == '' or vim.bo.buftype ~= '' then
    return
  end
  local top = vim.fn.line('w0')
  local bot = vim.fn.line('w$')
  local cursor_line = vim.api.nvim_win_get_cursor(0)[1]
  local line = cursor_line
  if top > 0 and bot > 0 and (cursor_line < top or cursor_line > bot) then
    line = math.floor((top + bot) / 2)
  end
  pcall(vim.fn.writefile, { path, tostring(line) }, cursor_file)
end

function _G.ObsidianSidecarOpenFile(path)
  if not path or path == '' then
    return 0
  end
  if vim.api.nvim_buf_get_name(0) == path then
    return 1
  end
  suppress_until = uv.now() + ${SUPPRESS_MS}
  vim.schedule(function()
    local escaped = vim.fn.fnameescape(path)
    pcall(vim.cmd, 'edit ' .. escaped)
  end)
  return 1
end

function _G.ObsidianSidecarShowEmptyBuffer()
  suppress_until = uv.now() + ${SUPPRESS_MS}
  vim.schedule(function()
    pcall(vim.cmd, 'enew')
  end)
  return 1
end

function _G.ObsidianSidecarSetCursor(line, path)
  if path ~= nil and path ~= '' and vim.api.nvim_buf_get_name(0) ~= path then
    return 0
  end
  local last = vim.api.nvim_buf_line_count(0)
  line = math.max(1, math.min(line, last))
  suppress_until = uv.now() + ${SUPPRESS_MS}
  pcall(vim.api.nvim_win_set_cursor, 0, { line, 0 })
  pcall(vim.cmd, 'normal! zz')
  return 1
end

function _G.ObsidianSidecarSetAutosave(enabled)
  vim.api.nvim_create_augroup('ObsidianSidecarAutosave', { clear = true })
  if enabled == 1 or enabled == true then
    vim.api.nvim_create_autocmd({ 'TextChanged', 'TextChangedI', 'InsertLeave', 'BufLeave' }, {
      group = 'ObsidianSidecarAutosave',
      pattern = '*',
      callback = function()
        if vim.bo.modified and not vim.bo.readonly and vim.fn.expand('%') ~= '' and vim.bo.buftype == '' then
          pcall(vim.cmd, 'silent! update')
        end
      end,
    })
  end
  return 1
end

function _G.ObsidianSidecarSetCursorSync(enabled)
  cursor_sync_enabled = (enabled == 1 or enabled == true)
  vim.api.nvim_create_augroup('ObsidianSidecarCursor', { clear = true })
  if cursor_sync_enabled then
    vim.api.nvim_create_autocmd({ 'CursorMoved', 'CursorMovedI', 'BufEnter', 'WinScrolled' }, {
      group = 'ObsidianSidecarCursor',
      callback = function()
        if timer then
          timer:stop()
        end
        timer = vim.defer_fn(push, ${DEBOUNCE_MS})
      end,
    })
  end
  return 1
end

_G.ObsidianSidecarSetAutosave(${autosave ? 'true' : 'false'})
_G.ObsidianSidecarSetCursorSync(${cursorSync ? 'true' : 'false'})

local function jump_to_heading(heading)
  if not heading or heading == '' then
    return false
  end
  heading = heading:gsub('^#+%s*', '')
  local escaped = vim.pesc(heading)
  local count = vim.api.nvim_buf_line_count(0)
  for i = 1, count do
    local line = vim.api.nvim_buf_get_lines(0, i - 1, i, false)[1] or ''
    if line:find('^#+%s+' .. escaped .. '%s*$') or line:find('^#+%s+' .. escaped) then
      pcall(vim.api.nvim_win_set_cursor, 0, { i, 0 })
      pcall(vim.cmd, 'normal! zz')
      return true
    end
  end
  return false
end

local function resolve_wikilink()
  local line = vim.api.nvim_get_current_line()
  local col = vim.api.nvim_win_get_cursor(0)[2] + 1
  local pattern = '%[%[([^%]]+)%]%]'
  local start_pos = 1
  while true do
    local s, e, match = line:find(pattern, start_pos)
    if not s then break end
    if col >= s and col <= e then
      local link_content = match:match('^([^|]+)') or match
      local target, heading = link_content:match('^([^#]*)#?(.*)$')
      target = target and vim.trim(target) or ''
      heading = heading and vim.trim(heading) or ''

      if target == '' and heading ~= '' then
        jump_to_heading(heading)
        return true
      end

      if target ~= '' then
        local candidates = {
          vault_root .. '/' .. target,
          vault_root .. '/' .. target .. '.md',
        }
        local cur_dir = vim.fn.expand('%:p:h')
        table.insert(candidates, cur_dir .. '/' .. target)
        table.insert(candidates, cur_dir .. '/' .. target .. '.md')

        local opened = false
        for _, path in ipairs(candidates) do
          if vim.fn.filereadable(path) == 1 then
            vim.cmd('edit ' .. vim.fn.fnameescape(path))
            opened = true
            break
          end
        end

        if not opened and vault_root ~= '' then
          local matches = vim.fn.globpath(vault_root, '**/' .. target .. '.md', 0, 1)
          if #matches > 0 and vim.fn.filereadable(matches[1]) == 1 then
            vim.cmd('edit ' .. vim.fn.fnameescape(matches[1]))
            opened = true
          end
        end

        if not opened then
          local new_path = (vault_root ~= '' and (vault_root .. '/' .. target .. '.md')) or (cur_dir .. '/' .. target .. '.md')
          vim.cmd('edit ' .. vim.fn.fnameescape(new_path))
          opened = true
        end

        if opened and heading ~= '' then
          vim.schedule(function()
            jump_to_heading(heading)
          end)
        end
        return true
      end
      break
    end
    start_pos = e + 1
  end
  return false
end

vim.api.nvim_create_autocmd('FileType', {
  pattern = { 'markdown', 'md' },
  callback = function(ev)
    vim.keymap.set('n', 'gf', function()
      if not resolve_wikilink() then
        pcall(vim.cmd, 'normal! gf')
      end
    end, { buffer = ev.buf, silent = true, desc = 'Follow wikilink or file' })
  end,
})
`;
}
