import { tmpdir } from 'node:os';
import { join } from 'node:path';

export const CURSOR_FILE = 'cursor';

const RUNTIME_DIR = join(tmpdir(), 'obsidian-neovim-sidecar');

export const CURSOR_SYNC_PATHS = {
	dir: RUNTIME_DIR,
	cursor: join(RUNTIME_DIR, CURSOR_FILE),
	lua: join(RUNTIME_DIR, 'sidecar.lua'),
	socket: join(RUNTIME_DIR, 'nvim.sock'),
};

// Whichever side moves last wins. Applying a move on one side makes that side
// emit its own change event, so each side ignores incoming moves for a moment
// after it applies one -- otherwise the echo bounces back and the two fight.
export const SUPPRESS_MS = 150;
export const DEBOUNCE_MS = 60;

export function buildSidecarLua(): string {
	return `-- generated by obsidian-neovim-sidecar; edits are overwritten
local uv = vim.uv or vim.loop
local cursor_file = '${CURSOR_SYNC_PATHS.cursor}'
local suppress_until = 0
local timer = nil

pcall(vim.fn.serverstart, '${CURSOR_SYNC_PATHS.socket}')

local function push()
  if uv.now() < suppress_until then
    return
  end
  local path = vim.api.nvim_buf_get_name(0)
  if path == '' then
    return
  end
  local line = vim.api.nvim_win_get_cursor(0)[1]
  pcall(vim.fn.writefile, { path, tostring(line) }, cursor_file)
end

function _G.ObsidianSidecarSetCursor(line, path)
  if path ~= nil and path ~= '' and vim.api.nvim_buf_get_name(0) ~= path then
    return 0
  end
  local last = vim.api.nvim_buf_line_count(0)
  line = math.max(1, math.min(line, last))
  suppress_until = uv.now() + ${SUPPRESS_MS}
  pcall(vim.api.nvim_win_set_cursor, 0, { line, 0 })
  pcall(vim.cmd, 'normal! zz')
  return 1
end

vim.api.nvim_create_augroup('ObsidianSidecarCursor', { clear = true })
vim.api.nvim_create_autocmd({ 'CursorMoved', 'CursorMovedI' }, {
  group = 'ObsidianSidecarCursor',
  callback = function()
    if timer then
      timer:stop()
    end
    timer = vim.defer_fn(push, ${DEBOUNCE_MS})
  end,
})
`;
}
